# 1. Database Connection
spring.datasource.url=jdbc:mysql://mysql-1d32efab-avanthi-f102.h.aivencloud.com:28913/defaultdb?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_GcSQFG0VxcNi3GTMALp

# 2. Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Server Port (Render needs 10000)
server.port=10000

# 4. Python AI backend URL
python.api.base-url=https://gramswaram-main.onrender.com